### ISSUE TITLE
Can this tool check android selinux policy?

### ISSUE THREAD

**Issue by tr4v3ler** [SELinuxProject/selint#288]
Fisrt I get policy file from an android device:
```adb pull /sys/fs/selinux/policy```

Then I use this tool on Ubuntu 22.04:
```selint ./policy```

But the output is:
```
Note: Skipping ./policy which is not a policy file
Note: Failed to load classes and perms probably due to running on a SELinux disabled system.
Note: Check E-007 is not performed because no permission macro has been parsed.
Note: Check E-008 is not performed because no class has been parsed.
```

**Comment by stephensmalley** [comment]
As per the README, SELinux is a program to perform static code analysis on SELinux policy source files, and it is only designed to work with policies based on the SELinux refpolicy. Not usable for compiled binary policies (which is what /sys/fs/selinux/policy returns) and not likely to work well with Android SELinux source policies since they are completely different and started from scratch rather than using refpolicy.
